language: php
php:
- 5.4
env:
  global:
  - secure: GGKZ4oIJfqYXRUDRRgG1rzwfkR+UpeFWWekalMZtsOjH7z9T4gtaL+x0IHxmePagIyAsMX0ZjJyEJNozMjG4coywzI1kThUYjDa3K977IijHag4Ln+0nXtNSSKOBjbg5hKQrIKg1vejaLQ8Iti58yXcBguZ08V5YtEsjhS0pVeA=
  - secure: X7k1BsqQ2mG+59Ysf1HUggMVjijC/6jHGP9PW6FZ3Te2tjsHTCRF/O7mzKQbnlRMsN10OA9Vta4E02LPI2jKfGuicCNRJUiy3NP/dlZRzZ47yBjxgsCnaq1SYz/1wHGncGIEa55309w6UkSxCy3duCxedhPwp2tz11Dorj1UhP8=
script: "./deploy.sh"
after_success: curl --ftp-create-dirs -v -T index.php -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bbankowski.nazwa.pl/index.php
