language: php
env:
  global:
  - secure: RyGrpyqekQvXRNfQgkJC9QECZPKJsJhe9ZtPv5iohp5BOnmzi4IqXL3vm30V3BIdgn5o1Crtrz4+IjyFG5GGnZbTjMYThYXrW7fi/q9393RWkgwCdu/9Guucs/H22mrfWv8bwj5MSBDiWVKwGZSdo74HfXss28CDkcfhUQJd9cw=
  - secure: DvK7VKT4WgDUFNuZrOEe5+LtsUfSzU810bbUL4FrA+0JnJlfklcyrQF6Jl5axsdRTXsGY09gEWSPv5VhgZR68Gdf2dRGFRH5GrLLxANq7ibdH7Enq8vwNrojPUtC24df6+cAFQeilZNZx5/9gq3W8aj6T8WCbOmy7wwJEr453bg=
after_success: curl --ftp-create-dirs -T uploadfilename -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bbankowski.nazwa.pl
