language: php
php:
- 5.4
env:
  global:
  - secure: c+eRnU/QJxck8EUZwsxhPsZeiTitrWlExaUx0b8K32EcQyMFFyy6hm2FpMNTnyIyjmYwf9Uel7jy36STjeQsNH/DEafNim7hHsoGXMWmjDTjGF3fd6qedceR99tksTuA8ZWcQ6z1lz5Hhvm62wgsFFNsJc3hnUXgmILKx7jbCt8=
  - secure: pye/cF8We2gGZoRFNAgZgX6rIRvsZc82fWrN0EkkQuKcc/OEOlDIcgKNxByA7DPwAJ7f3c7d+Ly86GxwuhQwnuJd0Cp3eePLfMnwueO3QQ80OIvBOOVkZSqt2dT8V97e85Jky1OXKnXs0fBo8rOjjCeXOWs8fH+N+QJt7yZQjnQ=
script: "./deploy.sh"
after_success:
  - lftp -c "open -u $FTP_USER,$FTP_PASSWORD ftp.bbankowski.nazwa.pl; put -O index.php index.php" 
#  - curl --ftp-create-dirs -v -T index.php ftp://$FTP_USER:$FTP_PASSWORD@ftp.bbankowski.nazwa.pl/
