language: php
php:
- 5.4
env:
  global:
  - secure: YF60C1Iwmi6i5tRfJTWXNri9+52DYrARUJhVH+4RtD7MqLXuYsGsVVYOJ0fN/NsruucAPJQfpsM/XP916kIwuAg0OrxeI5PoZG+HHEDcciqFMR4G4L+7zZJwj7xNKr7otualXqb0hQmA2Clchr909ry3yNzeA4VcDkhRjlrey18=
  - secure: MJazbue6RIPoeOvoQoWmzQxLSSUgrJ/opVs4AGz+n3xlQJZM+GzS8KjucfQ6bVxl5yI4A0paCnYt6p+ZKBYPgEiIYFEVsqvii9caKdjp8PmUryJo2EHAhKZ1rCy44pVVBF99aNhUpe2cdwwFcYv+aMXEBJiTdetlqn9VCDXg0NY=
script: "./deploy.sh"
after_success: curl --ftp-create-dirs -T index.php -u $FTP_USER:$FTP_PASSWORD ftp://ftp.bbankowski.nazwa.pl/index.php